/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * VelanDlg.java
 *
 * Created on 10/03/2010, 11:10:31
 */
package botoseis.ivelan.dialogs;

/**
 *
 * @author gabriel
 */
public class VelanDlg extends javax.swing.JDialog {

    /**
     * Creates new form VelanDlg
     */
    boolean ret;

    public VelanDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public VelanDlg(java.awt.Frame parent, boolean modal, float vMax, float vMin, int nv) {
        super(parent, modal);
        initComponents();
        tVmax.setValue(vMax);
        tVmin.setValue(vMin);
        tNvel.setValue(nv);
        m_vmin_default = vMin;
        m_vmax_default = vMax;
        m_nv_default = nv;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        l_vMin = new javax.swing.JLabel();
        l_numV = new javax.swing.JLabel();
        l_vMax = new javax.swing.JLabel();
        tVmin = new javax.swing.JFormattedTextField();
        tNvel = new javax.swing.JFormattedTextField();
        tVmax = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        cbPanel = new javax.swing.JCheckBox();
        cbAgc = new javax.swing.JCheckBox();
        cbGagc = new javax.swing.JCheckBox();
        cbQbal = new javax.swing.JCheckBox();
        cbPbal = new javax.swing.JCheckBox();
        cbMbal = new javax.swing.JCheckBox();
        cbMaxbal = new javax.swing.JCheckBox();
        cbJon = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfTpow = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfClip = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfEpow = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfGclip = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfGpow = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfScale = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfWagc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfNorm = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfTrap = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfBias = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Semblance Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        l_vMin.setText("Minimum velocity:");

        l_numV.setText("Number of velocities:");

        l_vMax.setText("Maximum velocity:");

        tVmin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        tVmin.setText("0");

        tNvel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        tNvel.setText("0");

        tVmax.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        tVmax.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_numV)
                    .addComponent(l_vMin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tVmin, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_vMax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tVmax, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tNvel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_vMin)
                    .addComponent(l_vMax)
                    .addComponent(tVmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tVmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_numV)
                    .addComponent(tNvel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Set defaults...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Wiggle Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jPanel4.setPreferredSize(new java.awt.Dimension(382, 50));
        jPanel4.setLayout(new java.awt.GridLayout(2, 4));

        cbPanel.setText("panel");
        jPanel4.add(cbPanel);

        cbAgc.setText("agc");
        jPanel4.add(cbAgc);

        cbGagc.setText("gagc");
        jPanel4.add(cbGagc);

        cbQbal.setText("qbal");
        jPanel4.add(cbQbal);

        cbPbal.setText("pbal");
        jPanel4.add(cbPbal);

        cbMbal.setText("mbal");
        jPanel4.add(cbMbal);

        cbMaxbal.setText("maxbal");
        jPanel4.add(cbMaxbal);

        cbJon.setText("jon");
        jPanel4.add(cbJon);

        jPanel5.setPreferredSize(new java.awt.Dimension(306, 100));
        jPanel5.setLayout(new java.awt.GridLayout(5, 4));

        jLabel1.setText("tpow");
        jPanel5.add(jLabel1);

        tfTpow.setText("0");
        jPanel5.add(tfTpow);

        jLabel6.setText("clip");
        jPanel5.add(jLabel6);

        tfClip.setText("0");
        jPanel5.add(tfClip);

        jLabel2.setText("epow");
        jPanel5.add(jLabel2);

        tfEpow.setText("0");
        jPanel5.add(tfEpow);

        jLabel7.setText("gclip");
        jPanel5.add(jLabel7);

        tfGclip.setText("0");
        jPanel5.add(tfGclip);

        jLabel3.setText("gpow");
        jPanel5.add(jLabel3);

        tfGpow.setText("0");
        jPanel5.add(tfGpow);

        jLabel8.setText("scale");
        jPanel5.add(jLabel8);

        tfScale.setText("0");
        jPanel5.add(tfScale);

        jLabel4.setText("wagc");
        jPanel5.add(jLabel4);

        tfWagc.setText("0");
        jPanel5.add(tfWagc);

        jLabel9.setText("norm");
        jPanel5.add(jLabel9);

        tfNorm.setText("0");
        jPanel5.add(tfNorm);

        jLabel5.setText("trap");
        jPanel5.add(jLabel5);

        tfTrap.setText("0");
        jPanel5.add(tfTrap);

        jLabel10.setText("bias");
        jPanel5.add(jLabel10);

        tfBias.setText("0");
        jPanel5.add(tfBias);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(174, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(80, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");
        jPanel3.getAccessibleContext().setAccessibleName("Wiggle Options");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ret = false;
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ret = true;
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        restoreToDefault();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void restoreToDefault() {
        tVmax.setValue(m_vmax_default);
        tVmin.setValue(m_vmin_default);
        tNvel.setValue(m_nv_default);

        tfEpow.setText("0.0");
        tfTpow.setText("0.0");
        tfGpow.setText("1.0");
        tfWagc.setText("0.5");
        tfTrap.setText("0.0");
        tfClip.setText("0.0");
        tfGclip.setText("1.0");
        tfScale.setText("1.0");
        tfNorm.setText("1.0");
        tfBias.setText("0.0");
    }

    public boolean isOK() {
        return ret;
    }

    public void setNV(int nv) {
        tNvel.setValue(nv);
    }

    public void setNVDefault(int nv) {
        m_nv_default = nv;
    }

    public void setVMax(float vMax) {
        tVmax.setValue(vMax);
    }

    public void setVMaxDefault(float vMax) {
        m_vmax_default = vMax;
    }

    public void setVMin(float vMin) {
        tVmin.setValue(vMin);
    }

    public void setVMinDefault(float vMin) {
        m_vmin_default = vMin;
    }

    public int getNV() {
        return Integer.parseInt(tNvel.getText());
    }

    public float getVMax() {
        return Float.parseFloat(tVmax.getText());
    }

    public float getVMin() {
        return Float.parseFloat(tVmin.getText());
    }

    public float getFloatValue(String parm) {
        if (parm.equals("tpow")) {
            return Float.parseFloat(tfTpow.getText());
        } else {
            if (parm.equals("epow")) {
                return Float.parseFloat(tfEpow.getText());
            } else {
                if (parm.equals("gpow")) {
                    return Float.parseFloat(tfGpow.getText());
                } else {
                    if (parm.equals("wagc")) {
                        return Float.parseFloat(tfWagc.getText());
                    } else {
                        if (parm.equals("trap")) {
                            return Float.parseFloat(tfTrap.getText());
                        } else {
                            if (parm.equals("scale")) {
                                return Float.parseFloat(tfScale.getText());
                            } else {
                                if (parm.equals("norm")) {
                                    return Float.parseFloat(tfNorm.getText());
                                } else {
                                    if (parm.equals("bias")) {
                                        return Float.parseFloat(tfBias.getText());
                                    } else {
                                        if (parm.equals("gclip")) {
                                            return Float.parseFloat(tfGclip.getText());
                                        } else {
                                            if (parm.equals("clip")) {
                                                return Float.parseFloat(tfClip.getText());
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        return 0f;
    }

    public boolean getBooleanValue(String parm) {
        if (parm.equals("panel")) {
            return cbPanel.isSelected();
        } else {
            if (parm.equals("jon")) {
                return cbJon.isSelected();
            } else {
                if (parm.equals("maxbal")) {
                    return cbMaxbal.isSelected();
                } else {
                    if (parm.equals("mbal")) {
                        return cbMbal.isSelected();
                    } else {
                        if (parm.equals("pbal")) {
                            return cbPbal.isSelected();
                        } else {
                            if (parm.equals("qbal")) {
                                return cbQbal.isSelected();
                            } else {
                                if (parm.equals("agc")) {
                                    return cbAgc.isSelected();
                                } else {
                                    if (parm.equals("gagc")) {
                                        return cbGagc.isSelected();
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        return false;
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbAgc;
    private javax.swing.JCheckBox cbGagc;
    private javax.swing.JCheckBox cbJon;
    private javax.swing.JCheckBox cbMaxbal;
    private javax.swing.JCheckBox cbMbal;
    private javax.swing.JCheckBox cbPanel;
    private javax.swing.JCheckBox cbPbal;
    private javax.swing.JCheckBox cbQbal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l_numV;
    private javax.swing.JLabel l_vMax;
    private javax.swing.JLabel l_vMin;
    private javax.swing.JFormattedTextField tNvel;
    private javax.swing.JFormattedTextField tVmax;
    private javax.swing.JFormattedTextField tVmin;
    private javax.swing.JTextField tfBias;
    private javax.swing.JTextField tfClip;
    private javax.swing.JTextField tfEpow;
    private javax.swing.JTextField tfGclip;
    private javax.swing.JTextField tfGpow;
    private javax.swing.JTextField tfNorm;
    private javax.swing.JTextField tfScale;
    private javax.swing.JTextField tfTpow;
    private javax.swing.JTextField tfTrap;
    private javax.swing.JTextField tfWagc;
    // End of variables declaration//GEN-END:variables

    private float m_vmin_default = 0.0f;
    private float m_vmax_default = 0.0f;
    private float m_nv_default = 0.0f;
}
